# Generated by Django 3.1.4 on 2021-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210108_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='territory',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_period_mn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_period_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
