# Generated by Django 2.2.10 on 2021-04-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employer', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=225)),
                ('fullname', models.CharField(blank=True, max_length=225, null=True)),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=225, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=225, null=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=225, null=True)),
                ('skype_id', models.CharField(blank=True, max_length=225, null=True)),
                ('alternate_contact', models.IntegerField(blank=True, null=True)),
                ('imo_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('district', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
