# Generated by Django 2.2.10 on 2021-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='task_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
