# Generated by Django 3.1.4 on 2021-01-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210121_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternate_contact',
            field=models.IntegerField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imo_number',
            field=models.IntegerField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skype_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
